### ISSUE TITLE
error when i click author link in single post

### ISSUE THREAD

**Issue by HsounaZinoubi** [rdlabo/ionic-wpcom#2]
Runtime Error
Cannot read property 'name' of undefined
Stack
TypeError: Cannot read property 'name' of undefined
    at SafeSubscriber._next (http://localhost:8100/build/3.js:16270:45)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/vendor.js:20723:16)
    at SafeSubscriber.next (http://localhost:8100/build/vendor.js:20670:22)
    at Subscriber._next (http://localhost:8100/build/vendor.js:20610:26)
    at Subscriber.next (http://localhost:8100/build/vendor.js:20574:18)
    at MapSubscriber._next (http://localhost:8100/build/vendor.js:36842:26)
    at MapSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:20574:18)
    at XMLHttpRequest.onLoad (http://localhost:8100/build/vendor.js:58628:38)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:9967)
    at Object.onInvokeTask (http://localhost:8100/build/vendor.js:4499:37)

**Comment by HsounaZinoubi** [comment]
and i get this error after upgrading ionic cli:

[12:57:15]  typescript: src/app/app.component.ts, line: 79 
            Type 'Timer' is not assignable to type 'number'. 

      L79:      this.intervalCurrentPage = setInterval(()=>{
      L80:        if(this.nav.getActive()){

**Comment by rdlabo** [comment]
thanks. I do updated Ionic version & name trubble.
